version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      timeout: 10s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  frontend:
    image: nginx
    ports:
      - 3005:80
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    image: node
    working_dir: /home/node/app
    volumes:
      - ./backend/:/home/node/app
    ports:
      - 3001:3000
    command: "node app.js"
    depends_on:
      db:
        condition: service_healthy


